version: '3.10'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: go run cmd/migrator/main.go

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - migrator
    ports:
      - "80:80"

volumes:
  pgdata: